export const API_ROUTER = {
  // coming soon
  GET_STATE: "/wishlist/get-state",
  GET_CITY: "/wishlist/get-city",
  CREATE_WISHLIST: "/wishlist/create-wishlist",
  GET_ALL_SPA: "/homepage-spa/get-all-spa",
  GET_SPA_LIST: "/homepage-spa/get-all-spa-list",
  GET_SPA_LIST_SLUGWISE: "/homepage-spa/get-all-spa-list-slugwise",
  GET_ALL_SPA_META_DATA: "/homepage-spa/get-all-spa-meta-data",
  GET_SPA_LIST_META: "/homepage-spa/get-all-spa-list-meta",
  GET_CITY_LIST: "/homepage-spa/get-sp-locations",
  GET_SPA_LIST_FOR_SEE_OTHER_CITY: "/homepage-spa/get-all-spa-list-see-other-cities",
  GET_ALL_SPA_LIST_SERVICES_SLUG: "/homepage-spa/get-all-spa-list-serviceslugwise",
  GET_ALL_SPA_LIST_SERVICES_SLUG_META: "/homepage-spa/get-all-spa-servicewise-meta-data",
  GET_MY_CURRENT_REVIEW_LIST: "/homepage-spa/top-spa-review",

  // AUTH
  LOGIN: "/serviceprovider/login",
  SIGNUP: "/serviceprovider/create",
  ADDVERIFYDOC: "/serviceprovider/add-serviceprovider-doc",
  FORGOT_PASSWORD: "/serviceprovider/forgot-password",
  VARIFY_OTP: "/serviceprovider/varify-otp",
  CHANGE_PASSWORD: "/serviceprovider/change-password",
  GET_DOC_STATUS: "/serviceprovider/get-doc-status",
  SEND_DELETE_USER_OTP: "/send-otp-user",
  VERIFY_DELETE_USER_OTP: "/varify-otp-user",
  BLOG: '/blog/blog-list',
  BLOG_DETAILS: '/blog/blog-detail',
  SPA_DETAILSL: 'homepage-spa/get-spa-details',
  GET_HOME_SERVICES_LIST: 'homepage-spa/get-my-services-list',
  GET_HOME_EMPLOYEE_LIST: 'homepage-spa/employee-list',
  GET_HOME_GALLERY: "homepage-spa/get-gallery",
  GET_HOME_REVIEW: "homepage-spa/get-review-list",
  GET_HOME_SERVICES: "homepage-spa/get-all-service-list",
  GET_HOME_SERVICES_PAGE: "homepage-spa/get-all-service-list-main",
  GET_ALL_SERVICES_LIST_HOME: "homepage-spa/get-all-service-list-home",
  BOOKING_WITHOUT_PAYMENT: "/homepage-spa/book-appointment-schedular-cms",
  BOOKING_WITHOUT_PAYMENT_NEW: "/schedularAppointmentQuick/book-appointment-schedular-cms",
  CONTACT_US: "/homepage-spa/contact-us",
  REQUEST_UD: "homepage-spa/request-more-info",
  NOTIFY_ME: "/serviceprovider/spa-notify",
  HOME_LIST_AMENITIES: "/homepage-spa/spa-amenities-list",
  GET_HOME_SERVICES_ID: "/homepage-spa/get-spa-serviceid",

  // dashboard
  GET_DETAILS: "/serviceprovider/get-details",
  GET_SERVICES: "/services/get-services",
  CREATE_SERVICE: "/services/create-service",
  UPDATE_SERVICE: "/serviceprovider/update",
  UPDATE_SERVICE_V3: "/update",
  GET_MY_SERVICES_LIST: "/services/get-my-services-list",
  GET_SERVICE_LIST_SUBSCRIPTION: "/services/get-service-list-subscription",
  GET_SERVICES_ALL: "/services/get-services-all",
  DELETE_SERVICE: "/services/delete-service",
  DISABLE_SERVICE: "/services/disable-service",
  SLOT_LIST: "/slot/slot-list",
  ADD_SLOT: "/slot/add-slot",
  GET_FAQS: "/faq-list",
  DELETE_SLOT: "/slot/delete-slot",
  GET_REVIEW: "/review/get-review-list",
  GET_GOOGLE_REVIEW: "/review/get-google-review",
  CREATE_REVIEW: "/review/create-review-reply",
  EDIT_REVIEW: "/review/edit-review-reply",
  DELETE_REVIEW: "/review/delete-review-reply",
  GET_GALLERY: "/services/get-gallery",
  GET_GALLERY_CATEGORY: "/services/get-gallery-category",
  CREATE_SERVICE_GALLERY: "/services/create-service-gallery",
  DELETE_GALLERY_IMAGE: "/services/delete-gallery-image",
  ANALYSTIC_LIST: "/analystic-list",
  SUBSCRIPTION_LIST: "/subscription/subscription-list",
  ADD_SPA_CUSTOMER: "/subscription/add-spa-customer",
  UPDATE_CUSTOMER_PLAN: "/subscription/update-customer-plan",
  CANCEL_SUBSCRIPTION: "/subscription/cancel-subscription",
  ADD_SPA_SUBSCRIPTION: "/subscription/add-spa-subscription",
  EDIT_SERVICE: "/services/edit-service",
  CHECK_BOOKABLE_SERVICE: "/services/check-bookable-service",
  CHECK_BANK_DETAILS: "/services/check-bank-details",
  CHECK_SUBSCRIPTION: "/dashboardSpa/check-subscription",
  GET_LIST_SPA_HOURS_SERVICE_PROVIDER: "/serviceprovider/spa-date-hours",
  ADD_EDIT_SPAHOURS_SERVICE_PROVIDER: "/serviceprovider/add-edit-spahours",
  ADD_EDIT_DATE_SCHEDULE: "/serviceprovider/add-edit-date-schedule",
  UPDATE_SPA_SCHEDULE: "/serviceprovider/update-spa-schedule",
  SPA_HOURS_DELETE_SERVICE_PROVIDER: "/serviceprovider/delete-spahours",
  GET_HOLIDAYS: "/serviceprovider/holidays",
  CREATE_HOLIDAY: "/serviceprovider/create-holiday",
  DELETE_HOLIDAY: "/serviceprovider/delete-holiday",

  //Employee
  ADD_EMPLOYEE: "/employee/add-employee",
  UPDATE_EMPLOYEE: "/employee/update-employee",
  UPDATE_EMPLOYEE_SCHEDULE_DATA: "/employee/update-employee-schedule-data",
  ADD_EDIT_EMPLOYEE_SCHEDULE: "/employee/add-edit-employee-schedule",
  ADD_EMPLOYEE_AVAILABILITY: "/employee/add-employee-avaliability",
  EMPLOYEE_SCHEDULE_DETAIL: "/employee/employee-schedule-details",
  MANAGE_EMPLOYEE_SCHEDULE: "/employee/manage-employee-schedule",
  ADD_EMPLOYEE_SCHEDULE: "/employee/add-employee-schedule",
  GET_EMPLOYEE_SCHEDULE: "/employee/get-employee-schedule",
  UPDATE_NEW_DATERANGE: "/employee/update-new-daterange",
  DELETE_EMPLOYEE_SCHEDULE: "/employee/delete-employee-schedule",
  UPDATE_EMPLOYEE_SCHEDULE: "/employee/update-employee-schedule",
  EMPLOYEE_LIST: "/employee/employee-list",
  DELETE_EMPLOYEE: "/employee/delete-employee",
  PHONE_VARIFY_OTP: "/employee/phone-varify-otp",
  PHONE_RESEND_OTP: "/employee/phone-resend-otp",
  EMPLOYEE_TIP: "employee/employee-tip",
  GET_EMPLOYEE_SERVICES: "/employee/get-services",
  ASSIGN_EMPLOYEE_SERVICES: "/employee/add-services",
  CHANGE_EMPLOYEE_STATUS: "/employee/change-status",
  ADD_EMPLOYEE_LEAVE_SCHEDULE: "/employee/add-leave-schedule",
  GET_EMPLOYEE_LEAVE_SCHEDULE: "/employee/get-leave-schedule",
  UPDATE_EMPLOYEE_LEAVE_SCHEDULE: "/employee/update-leave-schedule",
  DELETE_EMPLOYEE_LEAVE_SCHEDULE: "/employee/delete-leave-schedule",
  APPROVE_EMPLOYEE_LEAVE_SCHEDULE: "/employee/approve-leave-schedule",
  REJECT_EMPLOYEE_LEAVE_SCHEDULE: "/employee/reject-leave-schedule",
  ADD_LUNCH_BREAK: "/employee/add-lunch-break",
  EDIT_LUNCH_BREAK: "/employee/edit-lunch-break",
  GET_LUNCH_BREAKS: "/employee/get-lunch-breaks",
  DELETE_LUNCH_BREAK: "/employee/delete-lunch-break",
  GET_EMPLOYEE_DATE_RANGE: "/employee/get-employee-date-range",
  REMOVE_EMPLOYEE_SCHEDULE: "/employee/remove-employee-schedule",
  ACTIVE_EMPLOYEE_LIST: "/employee/active-employee-list",

  //Insights
  CRATE_ACCOUNT: "/accountDetails/create-btok-account",
  CREATE_STRIPE_ACCOUNT: "/accountDetails/create-stripe-account",
  GET_ACCOUNT_DETAIL: "/accountDetails/get-connected-account-detail",
  GET_SUBSCRIPTION_CARD_DETAIL: "/subscription/get-spa-card-detail",
  ADD_SPA_CARD: "/subscription/add-spa-card",
  UPDATE_SPA_DEFAULT_CARD: "/subscription/update-spa-default-card",
  DELETE_SPA_CARD: "/subscription/delete-spa-card",
  DELETE_STRIPE_ACCOUNT: "/accountDetails/delete-stripe-account",
  UPDATE_ACTIVE_STATUS: "/accountDetails/update-account-status",
  PAYMENT_HISTORY: "/payment-history",

  //Chat-Module
  CREATE_CHAT: "/chat/create-chat",
  CHAT_LIST: "/chat/chatlist",
  USER_TYPING: "/chat/userTyping",
  READ_STATUS: "/chat/readmessage",
  USER_CHAT_LIST: "/chat/user-chat-list",
  DELETE_CHAT: "/chat/remove-conversation",
  SUBSCRIBE_USER: "/chat/subscribeuser1",
  TOTAL_UNREAD_MSG: "chat/total-unread-msg",
  USER_LEAVE_ROOM: "/chat/leaveroom",

  //Admin-Chat APi's
  CREATE_ADMIN_CHAT: "/adminchat/create-chat",
  LIST_ADMIN_CHAT: "/adminchat/chatlist",
  READ_ADMIN_CHAT: "/adminchat/readmessage",
  TYPING_ADMIN_CHAT: "/adminchat/userTyping",
  DELETE_ADMIN_CHAT: "/adminchat/remove-conversation",
  ADMIN_USER_CHAT_LIST: "/adminchat/user-chat-list",
  ADMIN_LEAVE_ROOM: "/adminchat/leaveroom",

  //Notification
  NOTIFICATION_LIST: "/notification/notification-list",

  //Appointment
  GET_APPOINTMENT: "/calender/calender-list",
  GET_UPCOMING_APPOINTMENT_LIST: "/bookappointment/get-upcoming-booking-list",
  BOOKING_NO_SHOW: "/bookappointment/all-booking-no-show",
  UPCOMING_CALENDER_BOOKING_LIST: "/bookappointment/get-upcoming-calender-booking-list",
  GET_FAILED_PAYMENT_BOOKING_LIST: "/bookappointment/get-failed-payment-booking-list",
  CAPTURE_BOOKING_START_STATUS_CHARGE: "/bookappointment/all-capture-booking-start-status-charge",
  CREATE_CHECK_IN: "/bookappointment/create-check-in",
  UPDATE_COMPLETE_BOOKING_STATUS: "/bookappointment/all-update-complete-booking-status",
  CANCEL_BOOKING: "/bookappointment/all-cancel-booking-by-spa",
  GET_UNAVAILABLE_DATA: "/calender/calender-unavaliable-slot-list-daily",
  Get_WEEK_DATA: "/calender/all-employee-data-list-by-date-range",
  GET_SUMMARY_LIST_BY_DATE_RANGE: "/calender/get-summary-list-by-date-range",
  GET_SCHEDULES: "/calender/get-schedules",
  CANCEL_BOOKING_SEND_OTP: "/bookappointment/send-spa-cancel-otp",
  CANCEL_BOOKING_VERIFY_OTP: "/bookappointment/verify-spa-cancel-otp",
  CHECK_CLOSE_SPA_BOOKING: "/serviceprovider/check-close-spa-booking",
  CLOSE_SPA_TODAY: "/serviceprovider/close-spa-today",
  PRODUCT_LIST_BOOKING: "/pos/booking-product-list",
  REMOVE_BOOKING_TEMP_CART: "/poscart/remove-booking-temp-cart",
  ADD_PRODUCT_BOOKING_DATA: "/poscart/add-booking-temp-cart",
  UPDATE_PRODUCT_BOOKING_DATA: "/poscart/update-booking-temp-cart",
  ADD_TIP: "/capturePayment/add-employee-tip",
  DELETE_TIP: "/capturePayment/delete-employee-tip",
  DIRECT_COMPLETE: "/bookappointment/direct-complete-status",

  // capture payment
  create_payment_failed: "/capturePayment/create-payment-failed",
  CAPTURE_PAYMENT: "/capturePayment/capture-booking-payment",
  ADD_NEW_CARD: "/capturePayment/add-user-new-card",
  CAPTURE_CASH_PAYMENT: "/capturePayment/capture-cash-payment",
  FIVEMIN_REMINDER_DATA: "/capturePayment/get-fivemin-reminder-data",

  //Report
  ADD_USER_REPORT: "/report/add-sp-report",
  SPA_HELP: "/serviceprovider/spa-help",

  // pos
  POS_PRODUCT_LIST: "/pos/product/list",
  POS_PRODUCT_CREATE: "/pos/product/create",
  POS_PRODUCT_UPDATE: "/pos/product/update",
  POS_PRODUCT_COUNT: "/pos/product/get-product-count",
  ADD_PRODUCT: "/pos/add-product",
  POS_DELETE_PRODUCT: "/pos/product/delete",
  POS_ADD_TEMP_CART: "/poscart/add-temp-cart",
  POS_GET_PRODUCT: "/pos/get-product-details",
  POS_TEMP_CART_LIST: "/poscart/temp-cart-list",
  POS_REMOVE_TEMP_CART: "/poscart/remove-temp-cart",
  UPDATE_TEMP_CART: "/poscart/update-temp-cart",
  POS_EDIT_PRODUCT: "/pos/edit-product",
  POS_CHECKOUT: "/pos/pos-checkout",
  BOOKING_WISE_CART_ITEM_LIST: "/pos/booking-wise-cart-item-list",
  POS_ADD_ORDER_DETAILS: "/poscart/add-order-details",
  POS_ADD_CUSTOMER: "/poscart/add-pos-customer",
  POS_PAY_INVOICE: "/poscart/pay-pos-invoice",
  POST_ADD_CLIENT: "/pos/get-booked-user-list",
  POS_USER_DETAIL: "/user/",
  POS_CATEGORY_LIST: "/pos/category/list",
  POS_CATEGORY_CREATE: "/pos/category/create",
  POS_CATEGORY_UPDATE: "/pos/category/update",
  POS_CATEGORY_DELETE: "/pos/category/delete",
  POS_BRAND_LIST: "/pos/brand/list",
  POS_SALES_HISTORY_LIST: "/pos/sales-history/list",
  POS_INVENTORY_HISTORY_LIST: "/pos/inventory/get-inventory-history",
  POS_MANAGE_INVENTORY: "/pos/inventory/manage-inventory",

  // manual appointment
  GET_SERVICE_EMPLOYEE_LIST: "/manualAppointment/get-service-employee-list",
  GET_SERVICE_LIST: "/manualAppointment/get-services-list",
  GET_AVAILABLE_SLOT_LIST: "/manualAppointment/get-available-slot-list",
  BOOK_APPOINTMENT_SPA: "/manualAppointment/book-appointment-spa",
  UPDATE_BOOK_APPOINTMENT_SPA: "/manualAppointment/update-book-appointment-spa",
  CREATE_CASH_PAYMENT: "/manualAppointment/create-cash-payment",
  CREATE_ONLINE_PAYMENT: "/manualAppointment/create-manual-customer",
  CREATE_MANUAL_SUBSCRIPTION: "/manualAppointment/create-manual-booking-payment",
  CLICK_ON_CREATE: "/manualAppointment/rmv-pending-payment-data",
  ADD_MANUAL_NEW_CARD: "/manualAppointment/add-new-card",
  GET_CUSTOMER_CARD_DETAILS: "/manualAppointment/get-customer-card-details",
  EDIT_MANUAL_APPOINTMENT: "/manualAppointment/edit-book-appointment-spa",
  COMPLETE_SPA_APPOINTMENT: "/manualAppointment/complete-spa-appointment",


  //Insight Client
  GET_CLIENT_DATA: "/client-module/client-list",
  ADD_CLIENT_DATA: "/client-module/import-csv",
  ADD_CLIENT_DATA_INSIGHTS: "/client-module/add-record-manually",
  DELETE_CLIENT_DATA: "/client-module/delete-client",
  EDIT_CLIENT_DATA: "/client-module/update-client",
  GET_CLIENT_DETAIL: "/client-module/get-client-details",

  ADD_NOTES: "/client-module/notes/add",
  LIST_NOTES: "/client-module/notes/list",

  TOP_SPENDER: "/client-module/reports/top-sepnder",
  MOST_CANCEL_USERS: "/client-module/reports/cancellations-report-user-wise",
  CANCEL_USER_DATA_DETAIL: "/client-module/reports/cancellations-report-user-detail-wise",

  POS_HISTORY_LIST: "/client-module/history/pos-purchase-history",
  SERVICE_HISTORY_LIST: "/client-module/history/purchase-history",

  CSV_VERIFY: "/client-module/validate-csv-data",
  PAYMENT_HISTORY_CSV_DOWNLOAD: "/payment-history-download",

  // scheduler
  GET_SPA_ID: "/schedularAppointment/get-spa-id",
  GET_QUICK_SPA_ID: "/schedularAppointmentQuick/get-spa-id",
  GET_SERVICES_LIST: "/schedularAppointment/get-services-list",
  GET_QUICK_SERVICES_LIST: "/schedularAppointmentQuick/get-services-list",
  GET_SCHEDULAR_SERVICE_EMPLOYEE_LIST: "/schedularAppointment/get-service-employee-list",
  GET_QUICK_SERVICE_EMPLOYEE_LIST: "/schedularAppointmentQuick/get-service-employee-list",
  GET_SCHEDULAR_AVAILABLE_SLOT_LIST: "/schedularAppointment/get-available-slot-list",
  GET_FIXED_AVAILABLE_SLOT_LIST: "/schedularAppointmentQuick/get-available-fix-slot-list",
  GET_QUICK_AVAILABLE_SLOT_LIST: "/schedularAppointmentQuick/get-available-slot-list",
  BOOK_APPOINTMENT_SCHEDULAR: "/schedularAppointment/book-appointment-schedular",
  RMV_SCHEDULAR_PENDING_PAYMENT_DATA: "/schedularAppointment/rmv-schedular-pending-payment-data",
  CREATE_MANUAL_CUSTOMER: "/schedularAppointment/create-manual-customer",
  CREATE_MANUAL_PAYMENT: "/schedularAppointment/create-manual-booking-payment",
  CHECK_USER_PHONE: "/schedularAppointment/check-user-phone",

  // temp booking appointment
  TEMPBOOKAPPOINTMENT_CREATE: "/tempbookappointment/create",
  TEMPBOOKAPPOINTMENT_QUICK_CREATE: "/tempbookappointmentQuick/create",
  TEMPBOOKAPPOINTMENT_BOOK_GUEST: "/tempbookappointment/book-guest",
  TEMPBOOKAPPOINTMENT_update_book_guest: "/tempbookappointment/update-book-guest",
  TEMPBOOKAPPOINTMENT_UPDATE_MAIN_USER: "/tempbookappointment/update-main-user",
  TEMPBOOKAPPOINTMENT_QUICK_UPDATE_MAIN_USER: "/tempbookappointmentQuick/update-main-user",
  TEMPBOOKAPPOINTMENT_RMV_TEMP_DATA: "/tempbookappointment/rmv-temp-data",
  TEMPBOOKAPPOINTMENT_UPDATE_GUEST_DATA: "/tempbookappointment/update-guest-data",

  //Logout
  LOGOUT: "/serviceprovider/logout",

  CHECK_PHONE_NUMBER: "/manualAppointment/check-user-phone",

  //home page
  SPA_SLUG_LIST: "/site-map/spa-list",
  BLOG_SLUG_LIST: "/site-map/blog-list",
  SERVICE_SLUG_LIST: "/site-map/service-list",
  CITY_SLUG_LIST: "/site-map/city-list",
  GET_MOST_SEARCHED_SERVICE: "/homepage-spa/get-most-searched-service",

  // new-dashboard
  ADD_SHOWCASE_TEMP: "/dashboardSpa/add-showcase-temp",
  LIST_SHOWCASE_TEMP: "/dashboardSpa/list-showcase-temp",
  ADD_SHOWCASE_SUBMIT: "/dashboardSpa/add-showcase",
  LIST_SPAHOURS: "/dashboardSpa/list-spahours",
  ADD_EDIT_SPAHOURS: "/dashboardSpa/add-edit-spahours",
  LIST_SHOWCASE: "/dashboardSpa/list-showcase",
  DELETE_SHOWCASE: "/dashboardSpa/delete-showcase",
  UPDATE_SHOWCASE: "/dashboardSpa/update-showcase",
  LIST_AMENITIES: "/amenities/amenities-list",
  SPA_LIST_AMENITIES: "/amenities/spa-amenities-list",
  ADD_AMENITIES: "/amenities/spa-amenities-add",
  UPDATE_AMENITIES: "/amenities/spa-amenities-update",
  DELETE_AMENITIES: "/amenities/spa-amenities-delete",
  GET_DASHBOARD_BOOKING_LIST: "/dashboardSpa/bookinglist",
  DASHBOARD_BOOKING_APPROVED: "/dashboardSpa/bookingapproved",
  DASHBOARD_LEAD_TRACK: "/dashboardSpa/leadstracking",
  DASHBOARD_FINAL_BOOKING_APPROVED: "/dashboardSpa/finalbookingapproved",
  DASHBOARD_FINAL_BOOKING_REJECT: "/dashboardSpa/bookingrejected",
  DASHBOARD_SPA_HOURS_DELETE: "/dashboardSpa/delete-spahours",
  DASHBOARD_CONFIRMATION_STATUS_UPDATE: "/dashboardSpa/bookingconfirmed",
  DASHBOARD_LIST_SPAEMPLOYEE: "/spaEmployee/list-spaemployee",
  DASHBOARD_ADD_SPAEMPLOYEE: "/spaEmployee/add-spaemployee",
  DASHBOARD_UPDATE_SPAEMPLOYEE: "/spaEmployee/update-spaemployee",
  DASHBOARD_DELETE_SPAEMPLOYE: "/spaEmployee/delete-spaemployee",
  CHANGE_PASSWORD_EMPLOYEE: '/spaEmployee/update-password',
  DASHBOARD_ADD_SHOWCASE_TEMP_DETAILS: '/dashboardSpa/add-showcase-temp-details',
  DASHBOARD_BOOKING_FIXED_SLOT_LIST: '/dashboardSpa/bookingfixslot-list',
  DASHBOARD_BOOKING_SLOT_LIST: '/dashboardSpa/bookingslot-list',
  DASHBOARD_BOOKING_MANUAL_SLOT_DATA: '/dashboardSpa/bookingmanualslot-data',
  DASHBOARD_DELETE_TEMP_SHOWCASE: '/dashboardSpa/delete-temp-showcase',
  UPDATTE_SHOWCASE_STATUS: '/dashboardSpa/confirm-image-data',
  DASHBOARD_CHECK_PAST_APPOINTMENT: '/serviceprovider/check-pending-appointment',
  DASHBOARD_VIDEO_UPLOAD: '/spotlightVideo/upload-video',
  UPDATE_FEATURE_STATUS: '/spotlightVideo/update-spotlight-video-data',
  FETCH_INITIAL_VIDEO_SETTINGS: '/spotlightVideo/spotlight-video-list',
  SUBSCRIPTION_LIST_FOR_SPOTLIGHT_VIDEO: "/spotlightVideo/subscription-list",
  CREATE_SUBSCRIPTION_VIDEO_SPOTLIGHT: "/spotlightVideo/create-subscription-video-spotlight",
  CREATE_SUBSCRIPTION_FEATUTED_SPA: "/spotlightVideo/create-subscription-featured-spa",
  CANCEL_SUBSCRIPTION_VIDEO_SPOTLIGHT: "/spotlightVideo/cancel-subscription-video-spotlight",
  CANCEL_SUBSCRIPTION_FEATUTED_SPA: "/spotlightVideo/cancel-subscription-featured-spa",
  CREATE_MANUAL_SUBSCRIPTION_SPOTLIGHT_FEATUTED: "spotlightVideo/create-manual-subscription",
  GET_FEATURED_SPA_LIST: "homepage-spa/featured-spa-list",
  ADD_SPA_CARD_SPOTLIGHT: "/spotlightVideo/add-spa-card",
  SPOTLIGHT_ADD_SERVICE: "/spotlightVideo/add-service",

  // get-strted

  GET_CONTENT: "/pages/get-content",

  // Rooms
  ADD_ROOM: "/spa-room/add-room",
  EDIT_ROOM: "/spa-room/edit-room",
  DELETE_ROOM: "/spa-room/delete-room",
  LIST_ROOM: "/spa-room/list",
};
